services:
  postgresql_db:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nestjs_docker
      POSTGRES_USER: postgres
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - '5173:5173'
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - '5000:5000'




